name: floom
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  cloud_firestore: ^4.6.0
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  flutter:
    sdk: flutter
  flutter_custom_clippers: ^2.1.0
  flutter_gradient_colors: ^2.1.1
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.7.0
  google_fonts: ^4.0.4
  image_picker: ^0.8.7+4
  intl_utils: ^2.8.2
  introduction_screen: ^3.1.8
  jitsi_meet_wrapper: ^0.0.6
  pin_code_fields: ^7.4.0
  uuid: ^3.0.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
